server {
    listen 80;
    server_name localhost;

    client_max_body_size 50M;

    # Root endpoint (returns 404 since Nginx is only serving as an API gateway for local React app)
    location / {
        return 404 "Mindstec API Gateway. Please connect through http://localhost:5173 for the frontend.";
    }

    # Proxy /api/ requests to Django Gunicorn server
    location /api/ {
        proxy_pass http://django-backend:8000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy and rewrite /ai/ requests to FastAPI microservice internal endpoints
    location /ai/ {
        rewrite ^/ai/(.*)$ /api/v1/internal/$1 break;
        proxy_pass http://ai-service:8000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Serve media files directly from shared docker volume
    location /media/ {
        alias /app/media/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
