from typing import List, Optional
from pydantic import BaseModel, Field, field_validator
from app.models.retrieval import MetadataFilter


class RAGQueryRequest(BaseModel):
    """
    Validation schema for executing a Retrieval-Augmented Generation query.
    """
    question: str = Field(
        ...,
        min_length=1,
        description="The natural language question from the user."
    )
    tenant_id: Optional[str] = Field(
        default=None,
        description="Optional tenant identifier for tenant-specific filtering and multi-tenancy isolation."
    )
    category: Optional[str] = Field(
        default=None,
        description="Optional category to filter context chunks (e.g. policy, faq, product)."
    )
    filters: Optional[MetadataFilter] = Field(
        default=None,
        description="Optional fine-grained metadata filter constraints to pass to the retrieval engine."
    )
    top_k: Optional[int] = Field(
        default=None,
        ge=1,
        le=50,
        description="Maximum number of relevant chunks to retrieve. Overrides environment default if provided."
    )
    min_score: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Minimum similarity score threshold. Overrides environment default if provided."
    )
    provider: Optional[str] = Field(
        default=None,
        description="Override default LLM provider (e.g., openai, gemini, groq)."
    )
    model: Optional[str] = Field(
        default=None,
        description="Override default model name (e.g., gpt-4o, gemini-2.5-flash)."
    )

    @field_validator("question")
    @classmethod
    def question_not_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Question string cannot be empty or only whitespace.")
        return v

    class Config:
        json_schema_extra = {
            "example": {
                "question": "What is the vacation policy for new employees?",
                "tenant_id": "tenant_001",
                "category": "policy",
                "top_k": 3,
                "min_score": 0.70
            }
        }


class RAGCitation(BaseModel):
    """
    Represents a verified document reference derived from context chunks used to ground the LLM response.
    """
    document_id: Optional[str] = Field(default=None, description="Unique identifier of the source document.")
    document_name: Optional[str] = Field(default=None, description="Filename or descriptive label of the document.")
    source: Optional[str] = Field(default=None, description="The original path, URI, or source tag of the document.")
    page: Optional[int] = Field(default=None, description="Specific page number of the source chunk, if available.")

    class Config:
        json_schema_extra = {
            "example": {
                "document_id": "doc_823",
                "document_name": "employee_handbook.pdf",
                "source": "https://mindstec.com/docs/handbook.pdf",
                "page": 12
            }
        }


class RAGQueryResponse(BaseModel):
    """
    Standardized payload returned by the RAG Orchestrator containing the answers and source attributions.
    """
    answer: str = Field(..., description="The conversational grounded answer generated by the LLM.")
    citations: List[RAGCitation] = Field(
        default_factory=list,
        description="Unique citations/source references derived from the retrieved documents."
    )
    confidence_score: Optional[float] = Field(
        default=None,
        description="Calculated confidence metric based on retrieval scores."
    )
    duration_seconds: float = Field(
        ...,
        description="Total duration in seconds taken to execute the retrieval and generation pipeline."
    )


class RAGContextResponse(BaseModel):
    """
    Payload containing the compiled and formatted context block along with citations.
    Useful for testing retrieval and prompt optimization in isolation.
    """
    context: str = Field(..., description="The compiled, deduplicated context string ready for LLM prompt insertion.")
    citations: List[RAGCitation] = Field(
        default_factory=list,
        description="The source documents that compose the context block."
    )
    token_count: int = Field(..., description="Estimated token count of the compiled context block.")
