# Generated by Django 5.2.8 on 2026-07-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_fieldwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_html', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category_meta', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='solutions/')),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('caps_side', models.CharField(blank=True, max_length=250, null=True)),
                ('caps', models.JSONField(blank=True, default=list)),
                ('brands', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='fieldwork',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='fieldwork',
            table=None,
        ),
    ]
