# Generated by Django 5.2.8 on 2026-07-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_solution_alter_fieldwork_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='title_html',
        ),
        migrations.AlterField(
            model_name='solution',
            name='caps_side',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='solution',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
