# Generated by Django 5.2.8 on 2026-07-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_remove_solution_title_html_alter_solution_caps_side_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='description',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='caps',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='caps_side',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='category_meta',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='image_alt',
        ),
        migrations.AlterField(
            model_name='solution',
            name='slug',
            field=models.CharField(max_length=100),
        ),
    ]
