# Generated by Django 5.2.8 on 2026-07-11 08:56

from django.db import migrations, models


def migrate_old_data_to_new(apps, schema_editor):
    CompanyPage = apps.get_model('adminpanel', 'CompanyPage')
    FAQ = apps.get_model('adminpanel', 'FAQ')
    Product = apps.get_model('adminpanel', 'Product')
    Policy = apps.get_model('adminpanel', 'Policy')
    Documentation = apps.get_model('adminpanel', 'Documentation')
    KnowledgeBase = apps.get_model('adminpanel', 'KnowledgeBase')

    # Migrate CompanyPage
    for item in CompanyPage.objects.all():
        obj = KnowledgeBase.objects.create(
            knowledge_type='company',
            title=item.title,
            content=item.content,
            is_active=True,
            version=item.version
        )
        KnowledgeBase.objects.filter(id=obj.id).update(
            created_at=item.created_at,
            updated_at=item.updated_at
        )

    # Migrate FAQ
    for item in FAQ.objects.all():
        obj = KnowledgeBase.objects.create(
            knowledge_type='faq',
            title=item.question,
            content=item.answer,
            is_active=True,
            version=item.version
        )
        KnowledgeBase.objects.filter(id=obj.id).update(
            created_at=item.created_at,
            updated_at=item.updated_at
        )

    # Migrate Product
    for item in Product.objects.all():
        obj = KnowledgeBase.objects.create(
            knowledge_type='product',
            title=item.name,
            content=item.description,
            is_active=True,
            version=item.version
        )
        KnowledgeBase.objects.filter(id=obj.id).update(
            created_at=item.created_at,
            updated_at=item.updated_at
        )

    # Migrate Policy
    for item in Policy.objects.all():
        obj = KnowledgeBase.objects.create(
            knowledge_type='policy',
            title=item.title,
            content=item.content,
            is_active=True,
            version=item.version
        )
        KnowledgeBase.objects.filter(id=obj.id).update(
            created_at=item.created_at,
            updated_at=item.updated_at
        )

    # Migrate Documentation
    for item in Documentation.objects.all():
        obj = KnowledgeBase.objects.create(
            knowledge_type='documentation',
            title=item.title,
            content=item.content,
            is_active=True,
            version=item.version
        )
        KnowledgeBase.objects.filter(id=obj.id).update(
            created_at=item.created_at,
            updated_at=item.updated_at
        )


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_companypage_documentation_faq_policy_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_type', models.CharField(choices=[('company', 'Company Page'), ('faq', 'FAQ'), ('product', 'Product'), ('policy', 'Policy'), ('documentation', 'Documentation')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'knowledge_base',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RunPython(migrate_old_data_to_new, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(name='CompanyPage'),
        migrations.DeleteModel(name='FAQ'),
        migrations.DeleteModel(name='Product'),
        migrations.DeleteModel(name='Policy'),
        migrations.DeleteModel(name='Documentation'),
    ]
