# Generated by Django 6.0.7 on 2026-07-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_knowledgebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Processing', 'Processing'), ('Pending Review', 'Pending Review'), ('Indexed', 'Indexed'), ('Failed', 'Failed')], default='Uploaded', max_length=20)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-updated_at'],
            },
        ),
    ]
