# Generated by Django 6.0.7 on 2026-07-13

from django.db import migrations, models


CENTRES = [
    ('Deshwal Waste Management', 'New Delhi', 'B1/14 Basement, EROS Apartment, 56, Nehru Place, New Delhi 110019', 'Mr. Ashwani', '9555999163'),
    ('Deshwal Waste Management', 'Manesar', 'Plot No. 292, Sector-7, IMT Manesar, Haryana 122050', 'Mr. Kishore', '9873592319'),
    ('Deshwal Waste Management', 'Ahmedabad', 'G/D No. 1051, Vishal Estate, Opp. Bharat Petrol Pump, Sarkhej Bavla Road, Taluka Sanand, Santhal, Ahmedabad 382210', 'Mr. Mukesh Parikh', '9727355189'),
    ('Deshwal Waste Management', 'Pune', 'Survey No. 119, Deokar Building, Pune Alandi Road, Kalas, Vishrantwadi, Pune 411015, Maharashtra', 'Mr. Samar Pan', '9834480443'),
    ('Deshwal Waste Management', 'Mumbai (Thane)', '105, Sewanti Chhaya Building, Dombivali East, Ayre Road, Kalyan-Dombivali, Thane, Mumbai 421201', 'Mr. Anjani Tripathi', '9643013881'),
    ('Deshwal Waste Management', 'Chennai', 'Survey No. 91 & 92/2, No. 1/33, Kumaran Rice Mill Compound, Tirupati Road, Vellavedu, Chennai 602107, Tamil Nadu', 'Mr. Gyaniram Choudhary', '9080113177'),
    ('Deshwal Waste Management', 'Jaipur', 'Plot No. 1, Sita Nagar 2, Heerapur Rajni Pura, Heerawala, Ajmer Road, Jaipur 302024, Rajasthan', 'Mr. Shravan Swami', '9261118000'),
    ('Deshwal Waste Management', 'Kolkata', '3/7, Jadavgarh, P.S. Garfa, Kolkata 700078', 'Mr. Indresh', '7415191708'),
    ('Deshwal Waste Management', 'Bengaluru', 'B-39, 3rd Cross Road, Near Bharat Sevashram Sangha, Jakkur, Bengaluru 560064, Karnataka', 'Mr. Lokesh', '9873592320'),
    ('Reliable Trans Logistics', 'New Delhi', 'B-13, Okhla Phase-2, New Delhi', 'Mr. Ibrahim', '9555493838'),
    ('Reliable Trans Logistics', 'Chennai', 'No. 389, Sembium Road, Kathevedu, Puzhal, Chennai 600066', 'Mr. Dwevdi', '9884309370'),
    ('Reliable Trans Logistics', 'Jammu', 'Panamma Chowk, Jammu 180001', 'Mr. Narender Kumar', '9419622202'),
    ('Reliable Trans Logistics', 'Patna', 'South Gandhi Maidan, behind IMA Hall, Slimpur Ohra, Patna 800001', 'Mr. Satendra Prasad', '9431079451'),
    ('Reliable Trans Logistics', 'Ranchi', 'Mahadeo Munda, Near Kali Mandir, Chutia, Ranchi 834001', 'Mr. Briju Kumar', '9113728020'),
    ('Reliable Trans Logistics', 'Ahmedabad', '23 Manorath Complex, Sarapur, Ahmedabad 380052', 'Mr. Rajesh Patel', '9374887483'),
    ('Reliable Trans Logistics', 'Mumbai (Bhiwandi)', 'Kolher Village, Near Kolher Vajan Kanta, Bhiwandi, Mumbai', 'Mr. Sanjay Kumar', '9999434721'),
    ('Reliable Trans Logistics', 'Kolkata', '161/1 M G Road, Bangur Building, Kolkata 700007', 'Mr. M Tiwari', '9831744758'),
    ('Reliable Trans Logistics', 'Bhubaneshwar', '24/711, Bhimpur, New Airport Road, Bhubaneshwar 751020', 'Mr. Basant', '9338933801'),
    ('Reliable Trans Logistics', 'Guwahati', 'A K Azad Road, Rehabari Tinali, Near Namghar, Guwahati', 'Mr. Raju', '7002649709'),
    ('Reliable Trans Logistics', 'Nagpur', 'J P Complex, MIDC T-Point, Amravati Road, Wadi, Nagpur 440024', 'Mr. Kailash', '9823361807'),
    ('Reliable Trans Logistics', 'Bengaluru (Nelamangala)', 'No. 63 A, Dasanapur, NH-4 Tumkur Road, Behind Hanuman Temple, Nelamangala, Bangalore 562123', 'Mr. Singh', '9379757223'),
    ('Reliable Trans Logistics', 'Pune', 'Lane No. 14, Opp. Municipal Garden, Tiger Nagar, Pune 411015', 'Mr. Deepak', '9730007723'),
    ('Reliable Trans Logistics', 'Jaipur', 'Plant No. 20, Dyanand Nagar, Jodla Power House, Bhandarana Road, Jaipur', 'Mr. Nawrang', '9351755333'),
    ('Reliable Trans Logistics', 'Ludhiana', 'Plot No. 17, Transport Nagar, Ludhiana', 'Mr. Birbal', '9316055333'),
    ('Reliable Trans Logistics', 'Chandigarh', 'SCO 1086-87, Cabin No. 7, Sector 22B, Chandigarh', 'Mr. Jaiver', '9312255333'),
    ('Reliable Trans Logistics', 'Hyderabad', '1-A 600/12, Prakash Nagar, Hyderabad', 'Mr. Jammal', '9346086996'),
    ('Reliable Trans Logistics', 'Raipur', 'Near Gurudwara, Station Road, Raipur', 'Mr. R. L. Sahu', '9302228182'),
]


def seed_collection_centres(apps, schema_editor):
    CollectionCentre = apps.get_model('adminpanel', 'CollectionCentre')
    CollectionCentre.objects.bulk_create([
        CollectionCentre(operator=operator, city=city, address=address, contact_name=contact_name, phone=phone)
        for operator, city, address, contact_name, phone in CENTRES
    ])


class Migration(migrations.Migration):
    dependencies = [('adminpanel', '0009_document')]

    operations = [
        migrations.CreateModel(
            name='CollectionCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('contact_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['operator', 'city']},
        ),
        migrations.RunPython(seed_collection_centres, migrations.RunPython.noop),
    ]
