# Generated by Django 6.0.7 on 2026-07-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_collectioncentre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnowledgeBase',
        ),
    ]
