# Generated by Django 5.2.8 on 2026-07-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_gallery_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='href',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
