# Generated by Django 5.2.8 on 2026-07-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_blog_content_alter_blog_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RegionContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('phone_display', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('office_name', models.CharField(blank=True, default='', max_length=200)),
                ('map_embed_url', models.URLField(blank=True, default='', max_length=500)),
                ('map_link', models.URLField(blank=True, default='', max_length=500)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='adminpanel.region')),
            ],
            options={
                'verbose_name': 'Region Contact',
                'verbose_name_plural': 'Region Contacts',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='team/')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='adminpanel.region')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
