# Generated by Django 5.2.8 on 2026-07-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_seed_default_regions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regioncontact',
            options={},
        ),
        migrations.CreateModel(
            name='RegionBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('website_url', models.URLField(blank=True, default='', max_length=300)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='adminpanel.region')),
            ],
            options={
                'verbose_name': 'Region Contact',
                'verbose_name_plural': 'Region Contacts',
            },
        ),
    ]
