# Generated by Django 5.2.8 on 2026-07-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_regionbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='hero_fact1_bold',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='region',
            name='hero_fact1_sub',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='region',
            name='hero_fact2_bold',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='region',
            name='hero_fact2_sub',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='region',
            name='hero_fact3_bold',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='region',
            name='hero_fact3_sub',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
