# Generated by Django 5.2.8 on 2026-07-16 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_add_hero_facts_to_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='hero_fact1_bold',
        ),
        migrations.RemoveField(
            model_name='region',
            name='hero_fact1_sub',
        ),
        migrations.RemoveField(
            model_name='region',
            name='hero_fact2_bold',
        ),
        migrations.RemoveField(
            model_name='region',
            name='hero_fact2_sub',
        ),
        migrations.RemoveField(
            model_name='region',
            name='hero_fact3_bold',
        ),
        migrations.RemoveField(
            model_name='region',
            name='hero_fact3_sub',
        ),
    ]
