# Generated by Django 5.2.8 on 2026-07-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_add_client_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='enabled_pages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
