# Generated by Django 6.0.7 on 2026-07-16 18:36

from django.db import migrations, models

def associate_existing_brands(apps, schema_editor):
    RegionBrand = apps.get_model('adminpanel', 'RegionBrand')
    Solution = apps.get_model('adminpanel', 'Solution')
    
    solutions = list(Solution.objects.all())
    if not solutions:
        return
        
    for brand in RegionBrand.objects.all():
        brand.solutions.add(*solutions)

class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_add_enabled_pages_to_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionbrand',
            name='solutions',
            field=models.ManyToManyField(blank=True, related_name='brands', to='adminpanel.solution'),
        ),
        migrations.RunPython(associate_existing_brands),
    ]
