# Generated by Django 6.0.7 on 2026-07-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_regionbrand_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='caps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='solution',
            name='caps_side',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='category',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='solution',
            name='fact',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='solution',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='solution',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
