# Generated by Django 6.0.7 on 2026-07-17 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_solution_caps_solution_caps_side_solution_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='caps',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='caps_side',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='category',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='fact',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='tags',
        ),
        migrations.AlterField(
            model_name='regioncontact',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='adminpanel.region'),
        ),
    ]
