# Generated by Django 6.0.7 on 2026-07-17 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_eventnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If this is a country/sub-region, select its parent region (e.g., Global).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_regions', to='adminpanel.region'),
        ),
    ]
